name: Deploy the page

on:
    push:
        tags:
            - 'v*'
jobs:
    deploy:
        runs-on: ubuntu-latest
        env:
            REACT_APP_ERGO_ASSEMBLER_URL: https://assembler.sigmastamp.ml:14747
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  # TODO: Update in future to 16 + make workflow how to update this dependency
                  node-version: '14'

            - name: Install dependencies
              run: npm ci

            - name: Lint
              run: npm run lint

            - name: Test
              run: npm run test

            - name: Prepare environment
              # TODO: Can be this done better?
              run: |
                  echo REACT_APP_BUILD_DATE=$(date --iso-8601=seconds) >> .env
                  echo "REACT_APP_BUILD_DETAILS_URL=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" >> .env

            - name: Build
              run: npm run build

            - name: Configurate GIT
              run: |
                  git config --global user.email "me@pavolhejny.com"
                  git config --global user.name "hejny"

            - name: Deploy on GitHub pages
              run: npx gh-pages --dist ./build --repo https://x-access-token:${{secrets.GITHUB_TOKEN}}@github.com/${GITHUB_REPOSITORY}.git
