name: Deploy the page

on:
    push:
        tags:
            - 'v*'
jobs:
    test:
        name: Test + Lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 17
            - run: npm ci
            - run: npm run lint
            - run: npm run test

    deploy:
        runs-on: ubuntu-latest
        needs: test
        env:
            REACT_APP_ERGO_ASSEMBLER_URL: https://assembler.sigmastamp.ml:14747
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 17

            - name: Install dependencies
              run: npm ci

            - name: Prepare environment
              # TODO: Can be this done better?
              run: |
                  echo >> .env
                  echo REACT_APP_BUILD_DATE=$(date --iso-8601=seconds) >> .env
                  echo "REACT_APP_BUILD_DETAILS_URL=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" >> .env

            - name: Build
              run: npm run build
              env:
                  NODE_OPTIONS: --openssl-legacy-provider

            - name: Configurate GIT
              run: |
                  git config --global user.email "me@pavolhejny.com"
                  git config --global user.name "hejny"

            - name: Deploy on GitHub pages
              run: npx gh-pages --dist ./build --repo https://x-access-token:${{secrets.GITHUB_TOKEN}}@github.com/${GITHUB_REPOSITORY}.git
