name: CI
on:
    push:
        branches: [main]
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  # TODO: Update in future to 16 + make workflow how to update this dependency
                  node-version: '14'

            - name: Install dependencies
              run: npm install --no-fund

            - name: Build
              run: npm run build

            - name: Configurate GIT
              run: |
                  git config --global user.email "me@pavolhejny.com"
                  git config --global user.name "hejny"

            - name: Deploy on GitHub pages
              run: npx gh-pages --dist ./build --repo https://x-access-token:${{secrets.GITHUB_TOKEN}}@github.com/${{env.GITHUB_REPOSITORY}}.git
